name: common
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none
environment:
  sdk: ">=3.5.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  mason: ">=0.1.0-dev.57 <0.1.0"
  path: ^1.8.3
  pubspec_parse: ^1.2.2
